FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y \
    python3 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g gatsby-cli serve

WORKDIR /app

COPY package.json ./

#RUN npm install --legacy-peer-deps
RUN npm install 

COPY . .

EXPOSE 9000

CMD ["sh", "-c", "npm run build && echo '--- Build OK --- Serving on http://localhost:9000' && npx serve public -l 9000"]
