services:
  run:
    build:
      context: .
      dockerfile: Dockerfile.run
    container_name: personal-site-run
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - personal_site_node_modules:/app/node_modules
    command: gatsby develop -H 0.0.0.0 -p 8000

  builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: personal-site-builder
    ports:
      - "8000:8000"
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - personal_site_node_modules:/app/node_modules
    command: bash

  static-build:
    build:
      context: .
      dockerfile: Dockerfile.static
    container_name: personal-site-static
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - static_node_modules:/app/node_modules

volumes:
  personal_site_node_modules:
  static_node_modules:
